// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	AUTH_TOKENS: KVNamespace;

	HRMOS_API_TOKEN: SecretKey;
	HRMOS_COMPANY_NAME: CompanyName;

	DISCORD_WEBHOOK_URL: string;
}
